//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FJ_Attachment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public byte[] CV { get; set; }
        public string Date_Time { get; set; }
    }
}
