//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FJ_BadReports
    {
        public int ID { get; set; }
        public Nullable<int> IDPost { get; set; }
        public Nullable<int> NumberOfReports { get; set; }
    }
}
