//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FJ_Sing_up
    {
        public int ID { get; set; }
        public string E_Mail { get; set; }
        public string Password { get; set; }
        public string Phone_Number { get; set; }
    }
}
